# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(828, 685)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.box_coll = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.box_coll.sizePolicy().hasHeightForWidth())
        self.box_coll.setSizePolicy(sizePolicy)
        self.box_coll.setMinimumSize(QtCore.QSize(300, 0))
        self.box_coll.setMaximumSize(QtCore.QSize(200, 16777215))
        self.box_coll.setObjectName("box_coll")
        self.horizontalLayout.addWidget(self.box_coll)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.layout_field = QtWidgets.QVBoxLayout()
        self.layout_field.setObjectName("layout_field")
        self.verticalLayout.addLayout(self.layout_field)
        self.layout_btn = QtWidgets.QHBoxLayout()
        self.layout_btn.setObjectName("layout_btn")
        self.btn_find = QtWidgets.QPushButton(Dialog)
        self.btn_find.setObjectName("btn_find")
        self.layout_btn.addWidget(self.btn_find)
        self.btn_void = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_void.sizePolicy().hasHeightForWidth())
        self.btn_void.setSizePolicy(sizePolicy)
        self.btn_void.setObjectName("btn_void")
        self.layout_btn.addWidget(self.btn_void)
        self.btn_select = QtWidgets.QPushButton(Dialog)
        self.btn_select.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_select.sizePolicy().hasHeightForWidth())
        self.btn_select.setSizePolicy(sizePolicy)
        self.btn_select.setObjectName("btn_select")
        self.layout_btn.addWidget(self.btn_select)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_btn.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.layout_btn)
        self.table = QtWidgets.QTableWidget(Dialog)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.verticalLayout.addWidget(self.table)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Выберите ID"))
        self.btn_find.setText(_translate("Dialog", "Найти"))
        self.btn_void.setText(_translate("Dialog", "Выбрать пустой"))
        self.btn_select.setText(_translate("Dialog", "Выбрать"))
